### ISSUE TITLE
Odd timezone boundaries in Antarctica

### ISSUE THREAD

**Issue by jannikmi** [evansiroky/timezone-boundary-builder#104]
A user pointed out to me that the timezone boundaries in Antarctica seem to be off ([Issue](https://github.com/jannikmi/timezonefinder/issues/123)). Can you comment on this behavior? Here is a GUI view the issue: https://timezonefinder.michelfe.it/gui/0_133.24218750000003_-72.39570570653261

**Comment by kohenkatz** [comment]
`timezones.json` says:

```
  "Antarctica/DumontDUrville": [
    {
      "op": "init",
      "source": "manual-polygon",
      "data": [[[120,-70],[135,-70],[150,-70],[160,-70],[160,-65],[150,-65],[135,-65],[120,-65],[120,-70]]],
      "description": "Best guess at extent of DumontDUrville timezone based off of map at https://en.wikipedia.org/wiki/Time_in_Antarctica, but subtracting area for Concordia Station (Australia/Perth)."
    }
  ],
```

From this description, we see that Australia/Perth is there because of Concordia Station.

According to Wikipedia's [list of south pole stations] (https://en.wikipedia.org/wiki/Research_stations_in_Antarctica#List_of_research_stations), Concordia is at UTC+10, but I have not (yet) found a source for why that is.

**Comment by jannikmi** [comment]
Thank. That is what I imagined.

**Comment by evansiroky** [comment]
Closing until further information can be provided to indicate what correction is needed.
