### ISSUE TITLE
operlapping zones between Croatia and Serbia

### ISSUE THREAD

**Issue by szjozsef** [evansiroky/timezone-boundary-builder#114]
As of the actual settings for a few regions between Croatia and Serbia there is no time zone allocated, resulting in adding portions from the generic ETC-1 Ocean TimeZone to this continental regions.
On way that I figured out was to using this configuration:
```
  "Europe/Belgrade": [
    {
      "op": "init",
      "source": "manual-polygon",
      "data": [[[18.8250732421875,45.53184588624152],[18.979568481445312,45.53184588624152],[18.979568481445312,45.84602106744843],[18.8250732421875,45.84602106744843],[18.8250732421875,45.53184588624152]]],
      "description": "try to fix the holes between HR RS"
    }, {
      "op": "difference",
      "source": "overpass",
      "id": "Croatia"
    }, {
      "op": "union",
      "source": "overpass",
      "id": "Republic of Kosovo"
    }, {
      "op": "union",
      "source": "overpass",
      "id": "Serbia"
    }
  ],
  "Europe/Zagreb": [
    {
      "op": "init",
      "source": "manual-polygon",
      "data": [[[18.8250732421875,45.53184588624152],[18.979568481445312,45.53184588624152],[18.979568481445312,45.84602106744843],[18.8250732421875,45.84602106744843],[18.8250732421875,45.53184588624152]]],
      "description": "try to fix the holes between HR RS"
    }, {
      "op": "difference",
      "source": "overpass",
      "id": "Serbia"
    }, {
      "op": "union",
      "source": "overpass",
      "id": "Croatia"
    }
  ],
```

Maybe you find a better way to do this.

**Comment by evansiroky** [comment]
The little bits of `Etc/GMT-1` along that border have been left there intentionally by myself. The [Wikipedia article](https://en.wikipedia.org/wiki/Croatia%E2%80%93Serbia_border_dispute) noted in the expectedZoneOverlaps.json file notes that portions of the formal border claims result in "Terra nullius", that is no formal claim by either country. I believe all of these bits of Terra Nullius are uninhabited anyways, so that has been my rationale for allowing those little holes to exist. I am open to further discussion if community input indicates a preference to assign them to either country.

**Comment by rmathar** [comment]
See also https://github.com/RomanIakovlev/timeshape/issues/89 for places near sea shores which are unexpectedly assigned to the Etc zones.

**Comment by evansiroky** [comment]
RomanIakovlev/timeshape#89 is expected behavior as timezone-boundary-builder seeks to use the territorial waters of countries when creating timezone boundaries.
