### ISSUE TITLE
Upload to Wikipedia

### ISSUE THREAD

**Issue by mj1856** [evansiroky/timezone-boundary-builder#12]
Hi Evan,

I think your rendering of the time zone maps would fit better than the older image of the tz_world data shown on Wikipedia here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

Would you either please grant permission to release the rendered image under one of the Creative Commons licenses accepted on Wikimedia Commons, or perhaps just upload it there yourself?

Thanks a lot.
-Matt

**Comment by evansiroky** [comment]
Hey Matt!

Thanks for creating this issue.  I thought about editing the article, but I decided not to because the Wikipedia does not encourage edits made by individuals to promote their own work.  If you or anyone else wants to write about this project, go ahead!  Let me know what I would need to do to release the project image under a Creative Commons license.

Evan

**Comment by mj1856** [comment]
Create an account at [Wikimedia Commons](https://commons.wikimedia.org/wiki/Main_Page), then use the big blue "Upload" button on the main page and go through the wizard.  Just upload the rendered image.  Would be awesome if you can render it in svg, but the png is also acceptable.

LMK when you've uploaded it and give a link and I'll update the tz page.  Thanks.

**Comment by evansiroky** [comment]
I've uploaded it here: https://commons.wikimedia.org/wiki/File:2017a.png

**Comment by mj1856** [comment]
Thanks!  The tz list page now shows your image. :)
