### ISSUE TITLE
Update to Time Zone Database 2021e and future updates

### ISSUE THREAD

**Issue by sheridansmall** [evansiroky/timezone-boundary-builder#121]
Hi, I have been tasked with updating time-zone data for tens of thousands of locations as time-zones can change for a particular location. We intend to update these time-zones every 6 months to capture any changes that occur during this period. We were intending to use [timezonefinder](https://github.com/jannikmi/timezonefinder) which gets is data from [timezone-boundary-builder](https://github.com/evansiroky/timezone-boundary-builder). I started a discussion with the author of timezonefinder at https://github.com/jannikmi/timezonefinder/discussions/109 about how current the data was.

The latest release of timezone-boundary-builder is [2020d](https://github.com/evansiroky/timezone-boundary-builder/releases/tag/2020d) 05 Nov 2020 which I guess corresponds to release 2020d of https://www.iana.org/time-zones. However the latest release of https://www.iana.org/time-zones is 2021e (Released 2021-10-21).

I have noted the issue https://github.com/evansiroky/timezone-boundary-builder/issues/115 which mentions 2021b.

In order for me to complete that task I have been given I would need to update the time-zones for the locations in our data to those in https://www.iana.org/time-zones release 2021e. In addition I would need to be confident that every six months the time-zone data could be updated.

Please correct me if I'm wrong but my understanding is that timezone-boundary-builder (and timezonefinder) are using https://www.iana.org/time-zones release 2020d not 2021e.

Are there plans to update timezone-boundary-builder to use release 2021e and can I be confident that the data will be updated in the future.

**Comment by evansiroky** [comment]
I'm aware that there have been releases to the timezone database and that the current timezone-boundary-builder's release is not up-to-date. The release of `2021b` caused an immense amount of controversy on the timezone-database mailing list such that I have held off on updating due to the significant changes noted in #115. However, I also never got around to looking at the changes done in `2021c` until just now and have added an additional note on #115 about this.  

Given the updated trajectory of #115 which is to not merge a bunch of zones, I think the path forward to making a release may be simpler and less controversial. Furthermore, the renaming of `Pacific/Enderbury` to `Pacific/Kanton` only made it into my `2021b` branch in https://github.com/evansiroky/timezone-boundary-builder/commit/4c70c0cc36bf5bcfd36520e3e763a43c9573feee, so that is actually a thing that is release-worthy. So, I can commit to working on making a `2021e` release soon, but can't commit to an exact date when this'll be complete since I'm voluntarily doing this.

Regarding your 6 months expectation, that differs from this project's expectation which is noted in the README as follows:

> To maintain consistency with the timezone database, this project will only create a new release after the timezone database creates a new release. If there are no new timezones created or deleted in a timezone database release, then this project will only create a release if there have been changes performed to the boundary definitions of an existing zone within this project.

If this timeline is insufficient for you, the script in the repo is available for anyone to run at their own risk. This does pull in updated OSM Boundary data which could be useful depending on your use case.

**Comment by sheridansmall** [comment]
@evansiroky thanks for the reply and I do appreciate that you are doing this voluntary in your own time so thanks again.
It is good to hear that you can commit to working on making a 2021e release soon.
I will recommend to the stake holders in the project I'm working on that we update our location data every time there is a release of timezone-boundary-builder rather than every six months as originally planed given there will be "a new release after the timezone database creates a new release."

**Comment by evansiroky** [comment]
> I will recommend to the stake holders in the project I'm working on that we update our location data every time there is a release of timezone-boundary-builder rather than every six months as originally planed given there will be "a new release after the timezone database creates a new release."

I will reword that text to be more clear in the readme. This project sometimes does not create a new release along with every timezone database release. Often times a new timezone-boundary-builder release is not needed since all that could change in a timezone database release are the time rules of an existing timezone.

**Comment by evansiroky** [comment]
The readme has been updated, so I'm closing this issue.
