### ISSUE TITLE
Handling of timezones in China

### ISSUE THREAD

**Issue by c933103** [evansiroky/timezone-boundary-builder#13]
1. The Asia/Urumqi in Southern China should be removed. As the original coloring of that zone were based on dubious historical message, and more importantly no one in that area would actually use UTC+6, which is the current value for that Asia/Urumqi zone, therefore that area should not be Asia/Urumqi.
2. I can't find any sources for anyone in  Tibet and Qinghai area use UTC+6 time, as such it might not be appropriate to color them as Asia/Urumqi or Asia/Kashgar.
3. Because more than one time are used by different population in Xinjiang, I suggest coloring that area with strips of UTC+6 and UTC+8.
4. perhaps Asia/Kashgar, Asia/Harbin and Asia/Chongqing should be completely removed from the map as their existence in tz.db is only for legacy reason.

**Comment by evansiroky** [comment]
Thanks for bringing this up.  I think this is a good discussion from which to refactor the timezones of China into just 2 zones in this project.

See my responses to each item

1.  That always seemed like a mistake to me, but [it is mentioned in the timezone db](https://github.com/eggert/tz/blob/72a6e75f0bf5f04fdc8d26622e0b012c3b8294df/asia#L409-L420).  Also see [this thread on the timezone db email list](https://mm.icann.org/pipermail/tz/2006-July/013704.html).  However, as you note, nobody is likely to use that zone anymore since 1980.
2.  There are notes [in the timezone database](https://github.com/eggert/tz/blob/72a6e75f0bf5f04fdc8d26622e0b012c3b8294df/asia#L409-L427) of Tibet being on Xinjiang time.  Above those notes it also notes that eastern Qinghai (whatever that means) was on Long-Shu time which is now part of Asia/Shanghai.  I looked on wikipedia and it does seem that all of Qinghai is on Shanghai time.  Furthermore, the [wikipedia article about Xinjiang time](https://en.wikipedia.org/wiki/Xinjiang_Time) notes that it is primarily the ethnic Uyghur population that uses this time.  According to the demographics of Tibet and Qinghai, there is no Uyghur population in either of those regions.
3.  The primary goal of this project is to have a single zone be found at any coordinate, so I will not be overlapping these zones.  The software solution to this issue is to replace Asia/Urumqi or Asia/Kashgar w/ Asia/Shanghai if your worldview is that all of China is UTC+8.
4.  I agree with this proposal.  

My proposal is to have Asia/Urumqi be comprised of the Xianjiang region and have the rest of China become Asia/Shanghai.  This will greatly simplify the handling of zones and will result in less funky zone compilation from all the other geographies that are imported from OSM.

**Comment by c933103** [comment]
1. If you read a few mails down the source for that is from The American Atlas authored by Shanks which it have no source given in it. Seems like pure mistake just like the Asia/Ishigaki case.
2. Note that the description for Xin-zang Time ("Xinjiang-Tibet Time"), if you look at L385-390, are zones proposed in 1918 and deprecated in 1949 of the same file, and thus that is not relevant to the current usage.
2.a. Actually, some other ethnic minorities in Xinjiang also use Xinjiang Time. Edited the wikipedia to include that.
2.b. But officially the adoption of Xinjiang Time an announced made by provincal government in Xinjiang thus in theory it won't affect anywhere outside Xinjiang....
3./4. I see.
Having Asia/Urumqi comprise of Xinjiang region and Asia/Shanghai for rest of China seems good enough for now
