### ISSUE TITLE
Link with Time Zone Database on Iana

### ISSUE THREAD

**Issue by lpellegr** [evansiroky/timezone-boundary-builder#158]
I'm trying to comprehend the connection between IANA's Time Zone Database and this project.

I've observed that IANA's latest version is 2023c, while on this project, it's 2023b.

Is information from IANA's TZ Database utilized to define boundaries within this project?

Is the release naming convention for this project aligned with IANA's versions?

Understanding how this project aligns with IANA's latest updates would be crucial for contributions, especially when discrepancies arise between the two projects.

**Comment by evansiroky** [comment]
The IANA's TZ Database sort of contains boundary information in terms of general geographic descriptions, but this project defines the precise location of those boundaries in a GeoJSON and shapefile format.

Regarding your other questions, the Readme should hopefully be able to answer your question as follows:

> To maintain consistency with the timezone database, this project will only create a new release after the timezone database creates a new release. If there are no new timezones created or deleted in a timezone database release, then this project will only create a release if there have been changes performed to the boundary definitions of an existing zone within this project.

So, since the 2023c tz database release didn't include any new zones or zone deprecations, there was no need to create a new timezone-boundary-builder release. The reason the release is at 2023b is that I was still working on a 2023a timezone-boundary-builder release and when 2023b came out, so I just set the release to that version number.

**Comment by lpellegr** [comment]
Thanks a lot for the clarification.
