### ISSUE TITLE
Update to canonical names

### ISSUE THREAD

**Issue by mj1856** [evansiroky/timezone-boundary-builder#16]
One of my users pointed out that my library is returning `Asia/Rangoon` instead of `Asia/Yangon` for locations in Myanmar.  mj1856/GeoTimeZone#28

This appears to stem from the data in the `timezones.json` file [here](https://github.com/evansiroky/timezone-boundary-builder/blob/de3fb2bf091c13a0dae3e0621276f29c6796bca1/timezones.json#L3043).

Could you please check that the time zone ids are all canoncialized to the current `Zone` entries instead of `Link` entries?

Thanks.

**Comment by evansiroky** [comment]
Will do.  Thanks for bringing this to my attention.  So basically I should refactor any zone that appears in the 3rd column of the [backward file](https://github.com/eggert/tz/blob/master/backward) of the timezone database, right?

**Comment by mj1856** [comment]
Really, just any `Link` entry, regardless of which file its found in.  There are several links that are in the region files.

Sure, any consumer could resolve the link themselves, so it's not super critical - but there's no reason not to give the canonical `Zone` name.

**Comment by evansiroky** [comment]
Hmm, I looked at this a bit further and you're right that there are a bunch of links in the regions files. 
 Since the timezone database tries to have a zone for each nation-state I'm kind of leaning toward keeping those linked zone names in this project.  

The backward zones I'll definitely fix tho.  Here's a running list of my progress on refactoring them.

- [ ] America/Atikokan
- [ ] America/Coral_Harbour
- [ ] America/Montreal
- [ ] America/Toronto
- [x] Asia/Chongqing
- [x] Asia/Harbin
- [x] Asia/Kashgar
- [ ] Asia/Rangoon
- [x] Asia/Shanghai
- [x] Asia/Urumqi
- [ ] Asia/Yangon
- [ ] Pacific/Chuuk
- [ ] Pacific/Honolulu
- [ ] Pacific/Johnston
- [ ] Pacific/Yap

**Comment by mj1856** [comment]
Sure.  If the only entry for a given nation-state is a link to a zone that is in a different nation-state, then use the link.  Otherwise, use the zone.  That makes sense.
