### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by Solodkiy** [evansiroky/timezone-boundary-builder#25]
I can't generate shape file because of validation errors.
```
load zones into memory
do validation
Validation error: America/Argentina/Rio_Gallegos intersects America/Punta_Arenas area: 0.08795638367089173
Validation error: Asia/Chita intersects Asia/Shanghai area: 0.0007959703837724789
Validation error: Asia/Manila intersects Asia/Shanghai area: 0.21316446632400018
Validation error: Asia/Ust-Nera intersects Asia/Yakutsk area: 2.9578565029596997
Validation error: Europe/Ljubljana intersects Europe/Zagreb area: 0.005178844060499668
done
error! Zone validation unsuccessful
```

**Comment by evansiroky** [comment]
Thanks for the report.  Each of these need to be looked at individually to see what overlaps.

**Comment by Solodkiy** [comment]
@evansiroky Any news about this issue?

**Comment by evansiroky** [comment]
No, sorry, I haven't been able to investigate this yet.  As you may be able to see, grabbing and assembling data from the moving target that is OSM often results in discrepancies.  I'll make an effort to fix these issues sometime this month.  In the meantime, I'm open to accepting a pull request.

**Comment by evansiroky** [comment]
I'm going to start addressing these issues one-by-one in this thread.

## America/Argentina/Rio_Gallegos intersects America/Punta_Arenas:

The Viedma Glacier area keeps on changing in OSM.  Since I last looked there now appear to be boundaries for the Chilean provinces.

<img width="652" alt="screen shot 2017-10-14 at 8 20 40 pm" src="https://user-images.githubusercontent.com/3112493/31581313-79907366-b11d-11e7-9499-5829bcf2697f.png">

Since this area is also claimed by Argentina, I'm going to add an operation to keep my current approach of drawing a straight line between the last agreed-upon points of the Argentina-Chile boundary.

**Comment by evansiroky** [comment]
## Asia/Kathmandu intersects Asia/Kolkata

This is a new one that just came up with the latest OSM data.  It looks like someone added the [Kalapani territory](https://en.wikipedia.org/wiki/Kalapani_territory) to Nepal as well as India thus causing a validation error in this library.  According to the Wikipedia article, India is controlling that territory, so I'm going to add an operation that diffs Nepal with the Indian state of Uttarakhand.

**Comment by evansiroky** [comment]
## Asia/Manila intersects Asia/Shanghai

In OSM, someone added the disputed area of [Scarborough Shoal](https://en.wikipedia.org/wiki/Scarborough_Shoal) to the relation describing China as well as the relation describing the Philippines.  The Wikipedia article even says that Taiwan claims this shoal too.  For now, this library will assume the area is part of Asia/Manila since that is the closest area and that the Wikipedia article says fishermen from the Philippines fish there.

**Comment by evansiroky** [comment]
## Asia/Ust-Nera intersects Asia/Yakutsk

Not sure how it happened, but part of the Oymyakonsky District was erroneously getting included in Asia/Yakutsk.  I added an operation to make sure this doesn't happen in the future.

**Comment by evansiroky** [comment]
## Europe/Ljubljana intersects Europe/Zagreb

In the Adriatic Sea there is now a conflicting claim of territory for Croatia and Slovenia.  

<img width="644" alt="screen shot 2017-10-14 at 9 58 13 pm" src="https://user-images.githubusercontent.com/3112493/31581926-f63c8e56-b12a-11e7-8e37-9ad0a8af618e.png">


I'm going to add an operation to diff Croatia from Slovenia to fix this.

**Comment by evansiroky** [comment]
All right, the script ran without validation errors on my local machine.  I'm going to create a new issue to remind myself to create a wiki page about what to do when seeing validation issues.
