### ISSUE TITLE
Option to build timezone map without territorial water?

### ISSUE THREAD

**Issue by c933103** [evansiroky/timezone-boundary-builder#29]
Is it possible?

**Comment by evansiroky** [comment]
It is currently not possible.  What use case necessitates not having territorial waters?

**Comment by c933103** [comment]
Like to some who are not familiar with the territorial water area of some
countries, looking at the current version of the timezone map in east asia,
it could be harder to those people to visually identify the country they
want from map generated via this method.

2017-10-30 23:34 GMT+08:00 Evan Siroky <notifications@github.com>:

**Comment by evansiroky** [comment]
I see what you're saying.  At this point, the visual presentation of the data is not a priority for me since I believe the most relevant use case of this data is for use in computational timezone lookup libraries.  But if you are anyone else are so inclined, I'd be open to receiving a pull request with code that produces a shapefile that has shorelines.
