### ISSUE TITLE
Better model disputed territories in Doklam area

### ISSUE THREAD

**Issue by gknisely** [evansiroky/timezone-boundary-builder#49]
Hello,
I noticed that there is a hole at 89.0714, 27.5442 for the 2018d release of timezones.shapefile.zip vs timezones-with-oceans.shapefile.zip.  I assume that this is a disputed area based on some comments on openstreetmap.org; however, the hole exists in the timezones.shapefile.zip file but not the timezones-with-oceans.shapefile.zip file.

area at 89.0714, 27.5442 for timezones-with-oceans.shapefile.zip 
![image](https://user-images.githubusercontent.com/2676277/47436093-d3d59180-d773-11e8-9e82-dd187d843e0c.png)

versus area at 89.0714, 27.5442 for timezones.shapefile.zip
![image](https://user-images.githubusercontent.com/2676277/47436566-bead3280-d774-11e8-9496-97b0a212786d.png)

**Comment by evansiroky** [comment]
Aha!  You found that little spot.  In OpenStreetMap, the borders of all 3 bordering countries (Bhutan, China, India) don't seem to claim this area.  Therefore, the difference you see is that in the oceans shapefile, that area is actually Etc/GMT-6 because the boundary building script assigns all areas not covered by a country's boundary to the Etc/* zones.  It does actually look like there are some disputed border relations in OpenStreetMap, so it should be possible to add the claimed areas to each country's shape.

**Comment by evansiroky** [comment]
See this wikipedia article for info about border disputes in the area: https://en.wikipedia.org/wiki/Doklam

**Comment by gknisely** [comment]
Ok.  Thank you for the info and your time.  I had a feeling that was the issue.  Thanks again.

**Comment by kohenkatz** [comment]
Interestingly, Google Maps seems to have some border issues in this area too - the road map shows the Chinese "204 Provincial Road" as crossing the border into the disputed area while the satellite map shows it running along the border and never crossing it. The two maps are about 1500ft offset from each other.

**Comment by c933103** [comment]
Most online mapping services like Google Maps have trouble in mapping the border of China even when they're not disputed, because they want some level of security via obscurity and thus instructed all mapping service provider to use a coordinate system different from regular WGS84 when mapping China.
