### ISSUE TITLE
Africa/Johannesburg

### ISSUE THREAD

**Issue by ndw** [evansiroky/timezone-boundary-builder#54]
I happened to notice that the polygons for Africa/Johannesburg contain an odd vertical slice of Antarctica. I doubt that's intentional, but I could be mistaken.

**Comment by evansiroky** [comment]
This is intentional as part of the work for #42.  That area includes the area surrounding the Antarctic Research Station of [SANAE IV](https://en.wikipedia.org/wiki/SANAE_IV) which is part of the South African National Antarctic Program.  The Wikipedia article for SANAE IV suggests that the base uses the same timezone offset as South Africa, so this project assumed that the South Africa timezone is used in this area as well.  If you have information to the contrary, please reopen this issue.
