### ISSUE TITLE
Pacific/Auckland

### ISSUE THREAD

**Issue by ndw** [evansiroky/timezone-boundary-builder#55]
The bounding box for Pacific/Auckland seems to be incorrect:
```
-29.03033,-179.059153
-29.03033,179.364359
-52.821369,179.364359
-52.821369,-179.059153
-29.03033,-179.059153
```

**Comment by evansiroky** [comment]
This is due to [Raoul Island](https://en.wikipedia.org/wiki/Raoul_Island) being included as part of New Zealand and `Pacific/Auckland`.  The [Time in New Zealand](https://en.wikipedia.org/wiki/Time_in_New_Zealand) Wikipedia article doesn't include any indication that would suggest that Raoul Island uses a different timezone than the mainland, so I think it is correct to keep these islands as a part of `Pacific/Auckland`.

**Comment by ndw** [comment]
Ok. Perhaps I misunderstand something about the shapefile format. I'll stop bothering you.

I thought the bounding box was meant to cover the entire region governed by the timezone. New Zealand extends from -179 to at least -194 so the bounding box I extracted looks much too small.

**Comment by evansiroky** [comment]
You're not a bother at all!  I very much appreciate people double checking the work here.

New Zealand is tricky for making bounding boxes in the WGS projection because it has some parts to the left and right of the 180th meridian.  Therefore the bounding box appears to suggest that it stretches across almost the entire southern hemisphere.

**Comment by ndw** [comment]
Ah. That makes sense. That probably also explains the weird Leaflet behavior I'm seeing with polygons in New Zealand.

BTW, in case your curious, I'm using your map data and the IANA timezone files to drive the app at https://tzmap.nwalsh.com/ which, in turn, is just an example app demonstrating the underlying XQuery libraries.
