### ISSUE TITLE
expectedZoneOverlaps.json is complete list of the timezone overlapped area?

### ISSUE THREAD

**Issue by pdh0710** [evansiroky/timezone-boundary-builder#58]
expectedZoneOverlaps.json is "complete" list of the timezone overlapped area?
Here, "complete" means "as far as this project(=timezone-boundary-builder) knows".

Why all areas listed in expectedZoneOverlaps.json are rectangular shape?

**Comment by evansiroky** [comment]
Yes, it is a complete list of all overlapping area permitted to exist in the project.  This is to help during validation of the data because changing OSM data often causes certain boundaries to overlap when that is actually not desired.

They are all listed in a bounding box format because that is the simplest way to codify things, but it does potentially give too much freedom in how much boundaries can overlap.  It would perhaps be better to create a buffered shape for each overlap, but that would take some more effort.

I'm going to close this issue as it seems like a question, but if you see a need to change something in the boundary building process, please reopen and explain what needs to be changed.
