### ISSUE TITLE
Split Vietnam

### ISSUE THREAD

**Issue by c933103** [evansiroky/timezone-boundary-builder#66]
I have thought a bit more about it. Regardless of whether the project use backzone or not, Northern Vietnam will still be in a different timezone than Southern Vietnam in timezone database. (Southern Vietnam is always Asia/Ho_Chi_Minh, while Northern Vietnam is either Asia/Hanoi in backzone or Asia/Bangkok in the standard dataset.)

Thus, as the timezone-bondary-buioder's objective is to create a geographical correspondence for the tz database, it seems appropriate to split Vietnam to reflect this difference in tz database.

As for exactly how to split it into different zone, I guess https://en.wikipedia.org/wiki/Vietnamese_Demilitarized_Zone would be a reasonable starting point.

**Comment by evansiroky** [comment]
Your comment in #65 is quite relevant:

> The tricky thing here is Asia/Hanoi which have more data in the backzone tab and not just simply a link

I'm actually leaning towards using `Asia/Bangkok` to keep this library compatible with the current tz database. This would be the first area where a timezone identifier from another country will be used, but as you mention, it's probably the right thing to do.

As for geographic boundaries, it looks like the Quang Tri Province was the northernmost province of [South Vietnam](https://en.wikipedia.org/wiki/South_Vietnam), so that could be the boundary.

![South Vietnam Map](https://upload.wikimedia.org/wikipedia/commons/2/2d/Southvietmap.jpg)

Here's a link to [the relation in OSM](https://www.openstreetmap.org/relation/1895630).
