### ISSUE TITLE
Switch to ODC-By or PDDL licenses?

### ISSUE THREAD

**Issue by kueda** [evansiroky/timezone-boundary-builder#74]
I would like to use this time zone data to set time zones for the biodiversity observtions we have on [iNaturalist](https://www.inaturalist.org/) (currently time zones are semi-manually chosen and it's a big mess, surprise). However, the Share-Alike clause of the ODbL license you've chosen might be a deal breaker. If I'm reading the license correctly, if we pull these time zone shapes into a table in our database, we would be obliged to publish the entire database under the ODbL, right? We share a lot of our data openly, but obviously our entire database has a lot of sensitive information in it that we cannot publish. Even if you don't think that's the case, the legal uncertainty surrounding that is giving me hives. Would you consider switching to an ODC-By or PDDL license instead?

Related: who should be attributed, you (Evan Siroky), the Open Street Map contributors, or both? Should the attribution happen in our code base (e.g. in a README in [our github repo](https://github.com/inaturalist/inaturalist)), or on the live site?

**Comment by kohenkatz** [comment]
@kueda I'm not the creator of this project, but from my reading of the license it seems like you won't have a problem with it.  Specifically, this part:

>“Collective Database” – Means this Database in unmodified form as part of a collection of independent databases in themselves that together are assembled into a collective whole. A work that constitutes a Collective Database will not be considered a Derivative Database.

**Comment by evansiroky** [comment]
The ODbL was picked since that is the license that OpenStreetMap uses. It's certainly my intent to allow people to use this data without releasing all their other application data. As @kohenkatz notes, I'm pretty sure the ODbL explicitly allows this. IANAL, but section 4.5.a seems to be the relevant section of the ODbL that does not require the rest of your database to be shared publicly or to have the ODbL license as well.

I'm going to go ahead and close this issue, but if I am wrong about this and there are any further hindrances preventing you from using this data, then please re-open.

**Comment by kueda** [comment]
Many thanks for the replies.
