### ISSUE TITLE
Release 2019c

### ISSUE THREAD

**Issue by dnatic09** [evansiroky/timezone-boundary-builder#75]
Good afternoon friends and contributors,

We are huge fans and users of your TZ shapefiles.  Can you release the 2019c version of the shapefiles?  We have a use case requiring the latest changes in Brazil.

Best regards,

Dan Natic
The Weather Company / IBM

**Comment by evansiroky** [comment]
Hello, thanks for the request. A 2019c version hasn't been released yet as there weren't any new timezone ids that were created. Therefore, the 2019b release of timezone-boundary-builder should be compatible with the 2019c timezone database. However, certain changes that were made in OpenStreetMap could be included in an updated shapefile in which case a 2019c release could be warranted from this project. Were there specific changes in OpenStreetMap that are desired to be included in a 2019c release?

**Comment by dnatic09** [comment]
Hello!  We were running a 2018 version of the TZ database.  We had a few complaints about Brazil and Fiji.  We did not know if any geometries changed and wanted to make sure that everything would be compatible with the 2019c JVM TZ Database.  Given what you stated, I think we can live with the 2019b shapes for now without any major issues.

**Comment by juarezr** [comment]
I'm using version 2019b with [Timeshape Library](https://github.com/RomanIakovlev/timeshape) for Brazil and it's working correctly.

Brazil timezone changed in 2019 because **all daylight savings** after 2019-04-25 were repealed by a presidential decree [president's](http://legislacao.planalto.gov.br/legisla/legislacao.nsf/Viw_Identificacao/DEC%209.772-2019) [decree](https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2019/decreto/d9772.htm).

Previously the period for the savings was between the first Sunday of November and the third Sunday of February at 00:00-GMT-3.

This affected many systems where it accounted savings for the date ranges 2019-11-03 to 2020-02-16 result incorrectly in GMT-2 instead of the correct GMT-3. 

So anybody using a 2018 database has to upgrade to the 2019b version at least.

**Comment by evansiroky** [comment]
Closing as 2020a is now available.
