### ISSUE TITLE
Zone Id is different from developers.google.com/maps/documentation/timezone/get-api-key

### ISSUE THREAD

**Issue by skanagavelu** [evansiroky/timezone-boundary-builder#88]
I am using `https://github.com/evansiroky/timezone-boundary-builder/releases/tag/2020a` along with `RomanIakovlev/timeshape` code. 

When i try co-ordinates with lat/lang of `51.95874/85.95926` (Altai Republic, Siberian Federal District, Russia); 
i get zone id: "Asia/Barnaul", where as when i test with google api, i get zone id "Asia/Krasnoyarsk".

https://maps.googleapis.com/maps/api/timezone/json?location=51.95874,85.95926&timestamp=1602572121&key=XXXX

One more example is `Astrakhan` with lat: 46.34927, lng: 48.03384, we get `Europe/Astrakhan` instead of `Europe/Samara` from google api.

Is that needs update? Please help.

https://github.com/RomanIakovlev/timeshape/issues/69

**Comment by kohenkatz** [comment]
Are you sure this isn't a problem with `RomanIakovlev/timeshape`?

The [generated image of 2020a](https://raw.githubusercontent.com/evansiroky/timezone-boundary-builder/master/2020a.png) appears to show these zones correctly. I just ran a fresh build using `node --max-old-space-size=8192 index.js --filtered-zones "Asia/Barnaul,Asia/Krasnoyarsk"` and that gives the correct results too. I also tested with https://github.com/ugjka/go-tz and https://github.com/evansiroky/node-geo-tz/ and they both return the correct result with the 2020a data.

**Comment by evansiroky** [comment]
Both of these zones (`Asia/Barnaul` and `Europe/Astrakhan`) appear to have originated from [the 2016b release in the tzdb project](https://github.com/eggert/tz/blob/dc43ed5887d2b0a881790588097e2d3ca9a0c20a/NEWS#L1690-L1758). And both of these zones appear to have been created due to one or more jurisdictions changing their observed time from a timekeeping method that would've worked with the other zones you mention (`Asia/Krasnoyarsk` and `Europe/Samara` respectively). I believe that the data in this project reflects those changes correctly. Therefore, I believe that the Google API is incorrect.

**Comment by skanagavelu** [comment]
Thank you! @evansiroky, That might be the case where Google API may be incorrect.

**Comment by evansiroky** [comment]
Closing as it seems this project has the correct assumptions about timezones in this area.
