### ISSUE TITLE
result for Uzbek enclave

### ISSUE THREAD

**Issue by MrMinimal64** [evansiroky/timezone-boundary-builder#94]
Thanks for the latest release!
For version `2012d` I get an unexpected result with my package [`timezonefinder`](https://github.com/MrMinimal64/timezonefinder) for an Uzbek enclave at:
`latitude=40.0736177`
`longitude=71.0411812`

The result is  `Asia/Bishkek`, instead of the previous `Asia/Tashkent`.
Is that behavior desired or is there perhaps a bug in my package?

**Comment by evansiroky** [comment]
It appears that the borders of these timezones have had significant changes in this area due to changes in OpenStreetMap data. Shown below is a picture I screenshotted from QGIS. The red dotted line shows the previous borders from 2020a.

<img width="931" alt="Screen Shot 2020-11-06 at 12 19 08 PM" src="https://user-images.githubusercontent.com/3112493/98411207-8494ed80-202a-11eb-968c-df51162c4a11.png">

**Comment by MrMinimal64** [comment]
Thanks for looking into this. Indeed very interesting and politically relevant!
